[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  [dev.https]
    certFile = "localhost.pem"
    keyFile = "localhost-key.pem"                                          
  framework = "#custom"                                                    
  command = "npm run dev"             
  targetPort = 3000
  debug = true
  port = 8888
  publish = "dist"