<script lang="ts" setup>
const config = useRuntimeConfig();

// const story = await useAsyncStoryblok(
//   "test",
//   { version: "draft" },
//   { customParent: "https://app.storyblok.com" }
// );

const posts = ref([
  { css: "md:col-span-2", card: "1" },
  { card: "2" },
  { card: "3" },
  { card: "4" },
  { card: "5" },
]);

//const list = document.querySelector(".list");
const listRef = ref<HTMLUListElement>();
const itemRefs = ref([]);
// We want to know the width of one of the items. We'll use this to decide how many pixels we want our carousel to scroll.
const item = ref<HTMLLIElement>();
const scrollWidth = ref(0);

let isResizing = false;
const THROTTLE_TIME = 500; //ms
onMounted(() => {
  window.addEventListener("resize", handleWindowSizeChange);
  // window.addEventListener("resize", () => {
  //   if (!isResizing) {
  //     isResizing = true;
  //     handleWindowSizeChange();

  //     setTimeout(() => {
  //       isResizing = false;
  //     }, THROTTLE_TIME);
  //   }
  // });
  handleWindowSizeChange();
});
onUnmounted(() => {
  window.removeEventListener("resize", handleWindowSizeChange);
});

const handleWindowSizeChange = () => {
  const gap = convertRemToPixels(1.25); //1.25rem
  listRef.value; // <ul> element
  item.value = listRef.value?.children[0] as HTMLLIElement; // <li> element

  scrollWidth.value = listRef.value!.offsetWidth + gap; // item.value?.offsetWidth;
};

function convertRemToPixels(rem: number) {
  return rem * parseFloat(getComputedStyle(document.documentElement).fontSize);
}

function scroll(direction?: string) {
  // Based on the direction we call `scrollBy` with the item width we got earlier
  if (direction === "right") {
    listRef.value?.scrollBy({ left: -scrollWidth.value, behavior: "smooth" });
  } else {
    listRef.value?.scrollBy({ left: scrollWidth.value, behavior: "smooth" });
  }
}

function next() {
  scroll();
}

function prev() {
  scroll("right");
}

useHead({
  title: `test | ${config.public.app.name}`,
});
</script>

<template>
  <!-- <storyblok-component v-if="story" :blok="story.content" /> -->
  <div p-5 relative>
    <span absolute top-0 left-0>{{ scrollWidth }}</span>
    <!-- <div grid grid-cols-1 md:grid-cols-3 gap-5 class="hide-subsequent-rows"> -->
    <ul ref="listRef" class="scroll-x-grid">
      <template v-for="p in posts" :key="p">
        <li
          w-full
          min-h-82
          bg-bluegray
          :class="`center ${p.css}`"
          ref="itemRefs"
        >
          <div text-7xl>{{ p.card }}</div>
        </li>
      </template>
    </ul>

    <button @click="prev" text-primary absolute left-0 class="center-y">
      <div i-carbon:chevron-left text-4xl />
    </button>
    <button @click="next" text-primary absolute right-0 class="center-y">
      <div i-carbon:chevron-right text-4xl />
    </button>
  </div>
</template>

<style scoped>
.hide-subsequent-rows {
  grid-template-rows: 1fr;
  grid-auto-rows: 0; /* set height to 0 for autogenerated grid rows */
  overflow: hidden; /* hide grid items that overflow */
  padding-bottom: 0;
  row-gap: 0;
}

.scroll-x-grid {
  --n: 3; /*3 visible items */
  --g: 1.25rem;

  display: grid;
  grid-auto-flow: column;
  grid-auto-columns: calc((100% - (var(--n) - 1) * var(--g)) / var(--n));
  grid-gap: var(--g);

  overflow-x: auto;
  scroll-snap-type: x mandatory;
}
@media (max-width: 767px) {
  .scroll-x-grid {
    --n: 1; /*1 visible item */
  }
}

ui.scroll-x-grid li {
  max-width: 100%;
  scroll-snap-align: start;
}

.scroll {
  scrollbar-width: none; /* Firefox */
  -ms-overflow-style: none; /* IE & Edge */
}
.scroll::-webkit-scrollbar {
  display: none;
}
</style>
