<script setup lang="ts">
import useBreakpoints from "@/composables/useBreakpoints";
import type { Grid } from "@/storyblok/types";

const props = defineProps<{
  blok: Grid;
}>();

// const items = ref([
//   { id: "fyk", css: "md:col-span-2", card: "1", weight: 2 },
//   { id: "pkh", card: "2", weight: 1 },
//   { id: "dgd", card: "3", weight: 1 },
//   { id: "iib", card: "4", weight: 1 },
//   { id: "ytf", card: "5", weight: 1 },
// ]);
const items = ref(props.blok.grid_items);

//const grid = document.querySelector(".grid");
const gridRef = ref<HTMLUListElement>();
const itemRefs = ref<HTMLLIElement[]>([]);
const weightPerSlide = ref(1);

const { window_width, screen_size } = useBreakpoints();
watch(
  () => window_width.value,
  (width) => {
    if (width < screen_size.md) {
      weightPerSlide.value = 1;
    } else {
      weightPerSlide.value = 3;
    }
  },
  { immediate: true }
);

function move(direction?: string) {
  gridRef.value?.classList.add("fade-transition");
  const n = items.value.length;
  let w = 0;

  // Based on the direction we add/remove class 'hidden'
  if (direction === "right") {
    let i = 0;
    while (w < weightPerSlide.value) {
      w += items.value[i].weight;
      i++;
    }

    const hideItems = items.value.slice(0, i);
    const showItems = items.value.slice(i);
    items.value = [...showItems, ...hideItems];
    //console.log(i, "next: hide", hideItems, "show", showItems);
  } else {
    let i = n - 1;
    while (w < weightPerSlide.value) {
      w += items.value[i].weight;
      i--;
    }

    const showItems = items.value.slice(i + 1);
    const hideItems = items.value.slice(0, i + 1);
    items.value = [...showItems, ...hideItems];
    //console.log(i, "prev: hide", hideItems, "show", showItems);
  }

  setTimeout(() => {
    gridRef.value?.classList.remove("fade-transition");
    //gridRef.value!.style.transform = "";
  }, 230);
}

function next() {
  move("right");
}

function prev() {
  move("left");
}
</script>

<template>
  <div v-editable="blok" class="grid-carousel" relative>
    <div
      ref="gridRef"
      class="grid grid-cols-1 md:grid-cols-3 gap-5 hide-implicit-rows"
    >
      <!-- <template v-for="i in items" :key="i.id">
        <li
          ref="itemRefs"
          :class="`w-full min-h-82 bg-bluegray center ${i.css}`"
        >
          <div text-7xl>{{ i.card }}</div>
        </li>
      </template> -->
      <storyblok-component
        v-for="item in items"
        :key="item._uid"
        :blok="item"
      />
    </div>

    <button @click="prev" text-primary absolute left-0 class="center-y">
      <div i-carbon:chevron-left text-4xl />
    </button>
    <button @click="next" text-primary absolute right-0 class="center-y">
      <div i-carbon:chevron-right text-4xl />
    </button>
  </div>
</template>

<style scoped>
.hide-implicit-rows {
  grid-template-rows: 1fr;
  grid-auto-rows: 0; /* set height to 0 for autogenerated grid rows */
  overflow: hidden; /* hide grid items that overflow */
  padding-bottom: 0;
  row-gap: 0;
}

.fade-transition {
  animation: fadeIn 0.7s ease forwards;
}

@keyframes fadeIn {
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
}
</style>
